server:
  port: 8004
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/slowcodev1?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: sbsst
    password: sbs123414
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    #          ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDB53Dialect

  security:
    oauth2.client:
      registration:
        kakao:
          clientId: c28e370aebcafcb01c15c950a719bd03
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: http://localhost:8004/login/oauth2/code/kakao
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id


#전체 로그 레벨 설정(기본 info)
logging.level.root: info

#hello.springmvc 패키지와 그 하위 로그 레벨 설정
logging.level.itseasy.mark: debug

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 0
    refreshTokenExpiry: 60480000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

keycloak:
  realm: realmtest
  auth-server-url: http://localhost:8888/auth/
  ssl-required: external
  resource: clienttest
  use-resource-role-mappings: true
  bearer-only: true